/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SzolgaltatasokRouteImport } from './routes/szolgaltatasok'
import { Route as RolamRouteImport } from './routes/rolam'
import { Route as KapcsolatRouteImport } from './routes/kapcsolat'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AktualisAjanlatokRouteImport } from './routes/aktualis-ajanlatok'
import { Route as IndexRouteImport } from './routes/index'

const SzolgaltatasokRoute = SzolgaltatasokRouteImport.update({
  id: '/szolgaltatasok',
  path: '/szolgaltatasok',
  getParentRoute: () => rootRouteImport,
} as any)
const RolamRoute = RolamRouteImport.update({
  id: '/rolam',
  path: '/rolam',
  getParentRoute: () => rootRouteImport,
} as any)
const KapcsolatRoute = KapcsolatRouteImport.update({
  id: '/kapcsolat',
  path: '/kapcsolat',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AktualisAjanlatokRoute = AktualisAjanlatokRouteImport.update({
  id: '/aktualis-ajanlatok',
  path: '/aktualis-ajanlatok',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktualis-ajanlatok': typeof AktualisAjanlatokRoute
  '/blog': typeof BlogRoute
  '/galeria': typeof GaleriaRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktualis-ajanlatok': typeof AktualisAjanlatokRoute
  '/blog': typeof BlogRoute
  '/galeria': typeof GaleriaRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktualis-ajanlatok': typeof AktualisAjanlatokRoute
  '/blog': typeof BlogRoute
  '/galeria': typeof GaleriaRoute
  '/kapcsolat': typeof KapcsolatRoute
  '/rolam': typeof RolamRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktualis-ajanlatok'
    | '/blog'
    | '/galeria'
    | '/kapcsolat'
    | '/rolam'
    | '/szolgaltatasok'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktualis-ajanlatok'
    | '/blog'
    | '/galeria'
    | '/kapcsolat'
    | '/rolam'
    | '/szolgaltatasok'
  id:
    | '__root__'
    | '/'
    | '/aktualis-ajanlatok'
    | '/blog'
    | '/galeria'
    | '/kapcsolat'
    | '/rolam'
    | '/szolgaltatasok'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktualisAjanlatokRoute: typeof AktualisAjanlatokRoute
  BlogRoute: typeof BlogRoute
  GaleriaRoute: typeof GaleriaRoute
  KapcsolatRoute: typeof KapcsolatRoute
  RolamRoute: typeof RolamRoute
  SzolgaltatasokRoute: typeof SzolgaltatasokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/szolgaltatasok': {
      id: '/szolgaltatasok'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok'
      preLoaderRoute: typeof SzolgaltatasokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolam': {
      id: '/rolam'
      path: '/rolam'
      fullPath: '/rolam'
      preLoaderRoute: typeof RolamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapcsolat': {
      id: '/kapcsolat'
      path: '/kapcsolat'
      fullPath: '/kapcsolat'
      preLoaderRoute: typeof KapcsolatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktualis-ajanlatok': {
      id: '/aktualis-ajanlatok'
      path: '/aktualis-ajanlatok'
      fullPath: '/aktualis-ajanlatok'
      preLoaderRoute: typeof AktualisAjanlatokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktualisAjanlatokRoute: AktualisAjanlatokRoute,
  BlogRoute: BlogRoute,
  GaleriaRoute: GaleriaRoute,
  KapcsolatRoute: KapcsolatRoute,
  RolamRoute: RolamRoute,
  SzolgaltatasokRoute: SzolgaltatasokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
